version: '3.7'

services:
  backend:
    container_name: node-backend 
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true   
  front-end:
    container_name: react-front-end 
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true